# Generated by Django 3.2.15 on 2022-09-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeup',
            name='product',
        ),
    ]
