# Generated by Django 3.2.15 on 2022-09-08 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('makeups', '0002_remove_makeup_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeup',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
