# Generated by Django 3.2.15 on 2022-09-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeups', '0004_auto_20220908_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeup',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makeup',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
