# Generated by Django 3.2.15 on 2022-10-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220919_0509'),
        ('makeups', '0005_auto_20220918_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeup',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
