# Generated by Django 3.2.15 on 2023-02-17 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20220919_0509'),
        ('makeups', '0006_alter_makeup_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeup',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='작성자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makeup',
            name='price',
            field=models.IntegerField(default=1, verbose_name='메이크업 가격 (원/시간)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makeup',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'available'), ('u', 'unavailable')], default='a', help_text='Makeup availability', max_length=1),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='detail',
            field=models.TextField(verbose_name='메이크업 설명'),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='image',
            field=models.ImageField(upload_to='reference', verbose_name='메이크업 이미지'),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product', verbose_name='사용 제품들'),
        ),
        migrations.AlterField(
            model_name='makeup',
            name='title',
            field=models.CharField(max_length=100, verbose_name='메이크업 제목'),
        ),
    ]
