# Generated by Django 3.2.15 on 2023-02-17 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makeups', '0007_auto_20230217_0611'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='예약 시작 시간')),
                ('end_date', models.DateTimeField(verbose_name='예약 종료 시간')),
                ('total_fee', models.IntegerField(verbose_name='예약료')),
                ('status', models.CharField(blank=True, choices=[('d', 'Default'), ('r', 'Request'), ('a', 'Accept'), ('c', 'Completed')], default='d', help_text='reservation availability', max_length=1)),
                ('makeup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeups.makeup', verbose_name='메이크업 레퍼런스 이미지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='예약자')),
            ],
        ),
    ]
